### ISSUE TITLE
Error shard name (ameba) doesn't match dependency name (sqlite3) when deploying to heroku

### ISSUE THREAD

**Issue by CaDs** [veelenga/ameba#30]
I'm not sure this is an error on ameba itself, but I'm trying to deploy an amber application to heroku and the deploy is failing.

the error trace is

```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Amber app detected
remote: -----> Installing Crystal (v0.24.1 due to latest release at https://github.com/crystal-lang/crystal) from https://github.com/crystal-lang/crystal/releases/download/v0.24.1/crystal-0.24.1-2-linux-x86_64.tar.gz... done
remote: -----> Install project dependencies...
remote:
remote: Fetching https://github.com/amberframework/amber.git
remote: Fetching https://github.com/luislavena/radix.git
remote: Fetching https://github.com/jeromegn/kilt.git
remote: Fetching https://github.com/jeromegn/slang.git
remote: Fetching https://github.com/stefanwille/crystal-redis.git
remote: Fetching https://github.com/amberframework/cli.git
remote: Fetching https://github.com/mosop/optarg.git
remote: Fetching https://github.com/mosop/callback.git
remote: Fetching https://github.com/mosop/string_inflection.git
remote: Fetching https://github.com/amberframework/teeplate.git
remote: Fetching https://github.com/juanedi/micrate.git
remote: Fetching https://github.com/crystal-lang/crystal-db.git
remote: Fetching https://github.com/jwaldrip/shell-table.cr.git
remote: Fetching https://github.com/askn/spinner.git
remote: Fetching https://github.com/will/crystal-pg.git
remote: Fetching https://github.com/crystal-lang/crystal-mysql.git
remote: Fetching https://github.com/crystal-lang/crystal-sqlite3.git
remote: Fetching https://github.com/amberframework/granite-orm.git
remote: Fetching https://github.com/amberframework/quartz-mailer.git
remote: Fetching https://github.com/amberframework/smtp.cr.git
remote: Fetching https://github.com/amberframework/jasper-helpers.git
remote: Fetching https://github.com/amberframework/garnet-spec.git
remote: Fetching https://github.com/ysbaddaden/selenium-webdriver-crystal.git
remote: Installing amber (0.6.4)
remote: Installing radix (0.3.8)
remote: Installing kilt (0.4.0)
remote: Installing slang (1.7.1 at master)
remote: Installing redis (1.9.0)
remote: Installing cli (0.7.0)
remote: Installing optarg (0.5.8)
remote: Installing callback (0.6.3)
remote: Installing string_inflection (0.2.1)
remote: Installing teeplate (0.5.0)
remote: Installing micrate (0.3.0)
remote: Installing db (0.5.0)
remote: Installing shell-table (0.9.2)
remote: Installing spinner (0.1.1)
remote: Installing pg (0.14.1)
remote: Installing mysql (0.4.0)
remote: Installing sqlite3 (0.9.0)
remote: Installing granite_orm (0.8.2)
remote: Installing quartz_mailer (0.4.0)
remote: Installing smtp (0.3.0)
remote: Installing jasper_helpers (0.1.8)
remote: Installing garnet_spec (0.1.1)
remote: Installing selenium (0.3.0)
remote: done
remote: -----> Amber CLI not compiled... -----> Installing amber CLI... Fetching https://github.com/luislavena/radix.git
remote: Fetching https://github.com/jeromegn/kilt.git
remote: Fetching https://github.com/jeromegn/slang.git
remote: Fetching https://github.com/stefanwille/crystal-redis.git
remote: Fetching https://github.com/amberframework/cli.git
remote: Fetching https://github.com/mosop/optarg.git
remote: Fetching https://github.com/mosop/callback.git
remote: Fetching https://github.com/mosop/string_inflection.git
remote: Fetching https://github.com/amberframework/teeplate.git
remote: Fetching https://github.com/juanedi/micrate.git
remote: Fetching https://github.com/crystal-lang/crystal-db.git
remote: Fetching https://github.com/jwaldrip/shell-table.cr.git
remote: Fetching https://github.com/askn/spinner.git
remote: Fetching https://github.com/will/crystal-pg.git
remote: Fetching https://github.com/crystal-lang/crystal-mysql.git
remote: Fetching https://github.com/veelenga/ameba.git
remote: Error shard name (ameba) doesn't match dependency name (sqlite3)
remote:  !     Push rejected, failed to compile Amber app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to xxxx
remote:
```

As far as I can see I have no dependency to ameba inside my source, so I guess it might be required within any of the other shards.

Thanks a lot

**Comment by CaDs** [comment]
Just as a reference, this is the list of my app dependencies

``` yml
dependencies:
  amber:
    github: amberframework/amber
    version: 0.6.4

  granite_orm:
    github: amberframework/granite-orm
    version: ~> 0.8.2

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.4.0

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: ~> 0.1.6

  mysql:
    github: crystal-lang/crystal-mysql
    version: ~> 0.4.0

development_dependencies:
  garnet_spec:
    github: amberframework/garnet-spec
    version: ~> 0.1.1
```

**Comment by FrancoB411** [comment]
Hey, so I had the same issue, and I found ameba in lib/amber/shard.yml

<img width="466" alt="screen shot 2018-01-20 at 12 30 47 am" src="https://user-images.githubusercontent.com/320623/35180206-447d7fb8-fd79-11e7-84b6-466119e39a20.png">

I removed sqlite3, and the app built on Heroku.

**Comment by veelenga** [comment]
How do you deploy amber app? [heroku-buildpack-amber](https://github.com/amberframework/heroku-buildpack-amber)?

If so, this pull should solve it https://github.com/amberframework/heroku-buildpack-amber/pull/4. But anyway the error is a bit weird.

**Comment by CaDs** [comment]
Yes I’m using that build pack for deploying to heroku. 

I was suspecting that there was a missing production flag somewhere when installing the dependencies. 

The PR indeed seems to fix that issue. 

I will test it as soon as I go back home. 

Thanks a lot

**Comment by veelenga** [comment]
The problem is caused by these lines: https://github.com/amberframework/heroku-buildpack-amber/blob/master/bin/compile#L75-L76

After the `sed` command the `shard.yml` looks like this:

```
name: amber

version: 0.6.4

authors:
  - Elias Perez <<eliasjpr@gmail.com>>
  - Isaac Sloan <<isaac@isaacsloan.com>>
  - Dru Jensen <<drujensen@gmail.com>>
  - Nick Franken <<shnick@gmail.com>>
  - Benoit de Chezelles <<benoit.dechezelles@gmail.com>>

crystal: 0.24.1

license: MIT

targets:
  amber:
    main: src/amber/cli.cr

dependencies:
  radix:
    github: luislavena/radix
    version: ~> 0.3.8

  kilt:
    github: jeromegn/kilt
    version: ~> 0.4.0

  slang:
    github: jeromegn/slang
    branch: master

  redis:
    github: stefanwille/crystal-redis
    version: ~> 1.9.0

  cli:
    github: amberframework/cli
    version: ~> 0.7.0

  teeplate:
    github: amberframework/teeplate
    version: ~> 0.5.0

  micrate:
    github: juanedi/micrate
    version: ~> 0.3.0

  shell-table:
    github: jwaldrip/shell-table.cr
    version: ~> 0.9.1

  spinner:
    github: askn/spinner
    version: ~> 0.1.1

  pg:
    github: will/crystal-pg
    version: ~> 0.14.1

  mysql:
    github: crystal-lang/crystal-mysql
    version: ~> 0.4.0

  sqlite3:
    github: crystal-lang/crystal-sqlite3
    version: ~> 0.9.0
    github: veelenga/ameba
    version: ~> 0.4.0

```
